Presentation/Web/Ivh.Web.Patient/Areas/Mobile/Controllers/LegalController.cs
namespace Ivh.Web.Patient.Areas.Mobile.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Web.SessionState;
    using Application.Content.Common.Dtos;
    using Application.Content.Common.Interfaces;
    using Application.Core.Common.Interfaces;
    using Application.FinanceManagement.Common.Interfaces;
    using Attributes;
    using Common.VisitPay.Strings;
    using Common.Web.Controllers;
    using Common.Web.Interfaces;
    using Common.Web.Models.Legal;
    using Provider.Pdf;

    [GuarantorAuthorize(Roles = VisitPayRoleStrings.System.Patient + "," + VisitPayRoleStrings.Admin.Administrator)]
    [RequiresAcknowledgement(Enabled = false)]
    [RequiresSsoAuthorization(Enabled = false)]
    public class LegalController : BaseLegalController
    {
        public LegalController(
            Lazy<IBaseControllerService> baseControllerService,
            Lazy<IGuarantorApplicationService> guarantorApplicationService,
            Lazy<IContentApplicationService> contentApplicationService,
            Lazy<ICreditAgreementApplicationService> creditAgreementApplicationService,
            Lazy<IPdfConverter> pdfConverter)
            : base(baseControllerService, guarantorApplicationService, contentApplicationService, creditAgreementApplicationService, pdfConverter)
        {
        }
        
        [HttpGet]
        [Common.Web.Attributes.SessionState(SessionStateBehavior.ReadOnly)]
        public async Task<ActionResult> CreditAgreementPartial(int o)
        {
            ContentDto content = await this.CreditAgreementApplicationService.Value.GetCreditAgreementContentAsync(o);

            CreditAgreementViewModel model = new CreditAgreementViewModel
            {
                Text = content.ContentBody,
                Title = content.ContentTitle,
                IsExport = false,
                FinancePlanOfferId = o
            };

            return this.PartialView("_CreditAgreement", model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Legal()
        {
            return this.View();
        }
        
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Privacy()
        {
            return this.View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult PrivacyPartial()
        {
            return this.PartialView("_Privacy");
        }
    }
}

Presentation/Web/Ivh.Web.Patient/Controllers/LegalController.cs
namespace Ivh.Web.Patient.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Web.SessionState;
    using Application.Content.Common.Dtos;
    using Application.Content.Common.Interfaces;
    using Application.Core.Common.Interfaces;
    using Application.FinanceManagement.Common.Interfaces;
    using Attributes;
    using Common.Base.Utilities.Helpers;
    using Common.VisitPay.Enums;
    using Common.Web.Controllers;
    using Common.Web.Interfaces;
    using Common.Web.Models.Legal;
    using Common.Web.Models.Shared;
    using Ivh.Domain.FinanceManagement.FinancePlan.Entities;
    using Provider.Pdf;
    using System;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    [RequiresAcknowledgement(Enabled = false)]
    [RequiresSsoAuthorization(Enabled = false)]
    [GuarantorAuthorize]
    public class LegalController : BaseLegalController
    {
        private readonly Lazy<IFinancePlanApplicationService> _financePlanApplicationService;

        public LegalController(
            Lazy<IBaseControllerService> baseControllerService,
            Lazy<IGuarantorApplicationService> guarantorApplicationService,
            Lazy<IContentApplicationService> contentApplicationService,
            Lazy<ICreditAgreementApplicationService> creditAgreementApplicationService,
            Lazy<IPdfConverter> pdfConverter,
            Lazy<IFinancePlanApplicationService> financePlanApplicationService
            )
            : base(
                  baseControllerService,
                  guarantorApplicationService,
                  contentApplicationService,
                  creditAgreementApplicationService,
                  pdfConverter)
        {
            this._financePlanApplicationService = financePlanApplicationService;
        }

        [MobileRedirect("/mobile/Legal/")]
        [HttpGet]
        [AllowAnonymous]
        public override async Task<ActionResult> Index()
        {
            return await base.Index();
        }

        [HttpGet]
        [RequiresAcknowledgement(Enabled = true)]
        [Common.Web.Attributes.SessionState(SessionStateBehavior.ReadOnly)]
		public async Task<ActionResult> RetailInstallmentContract(string id)
        {
			int? financePlanOfferId = this.GetFinancePlanOfferId(id);
            if (!financePlanOfferId.HasValue)
			{
				return this.RedirectToAction("NotFound", "Error");

			} 

			ContentDto content = await this.CreditAgreementApplicationService.Value.GetCreditAgreementContentAsync(financePlanOfferId.Value);
	        CreditAgreementViewModel model = new CreditAgreementViewModel
	        {
		        Text = content.ContentBody,
                Title = content.ContentTitle,
		        IsExport = false,
		        FinancePlanOfferId = financePlanOfferId.Value
			};

	        return this.View("_CreditAgreementPage", model);
        }

        [HttpGet]
        [AllowOffline]
        [Common.Web.Attributes.SessionState(SessionStateBehavior.ReadOnly)]
        public async Task<ActionResult> CreditAgreementPartial(int o)
        {
            ContentDto content = await this.CreditAgreementApplicationService.Value.GetCreditAgreementContentAsync(o);

            CreditAgreementViewModel model = new CreditAgreementViewModel
            {
                Text = content.ContentBody,
                Title = content.ContentTitle,
                IsExport = false,
                FinancePlanOfferId = o
            };

            return this.PartialView("_CreditAgreement", model);
        }

        [HttpGet]
        [AllowOffline]
        [Common.Web.Attributes.SessionState(SessionStateBehavior.ReadOnly)]
        public async Task<ActionResult> CreditAgreementPdf(int o, int? v)
        {
            ContentDto content = await this.CreditAgreementApplicationService.Value.GetCreditAgreementContentAsync(o);

            this.ViewData.Model = new CreditAgreementViewModel
            {
                Text = content.ContentBody,
                Title = content.ContentTitle,
                IsExport = true,
                FinancePlanOfferId = o
            };

            string clientName = ReplacementUtility.ReplaceWhiteSpace(ReplacementUtility.RemoveNonAlphaNumeric(this.ClientDto.ClientName), "_");
            string agreementName = ReplacementUtility.ReplaceWhiteSpace(ReplacementUtility.RemoveNonAlphaNumeric(content.ContentTitle), "_");
            string fileName = $"{clientName}_{agreementName}.pdf";

            this.WritePdfInline(this.PdfConverter.Value.CreatePdfFromHtml($"{this.ClientDto.ClientName} {agreementName}", this.RenderViewToString("~/Views/Legal/_CreditAgreementPdf.cshtml", "~/Views/Shared/_LayoutPrint.cshtml")), fileName);

            return this.Json(new { }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult LegalPartial()
        {
            CmsVersionDto cmsVersion = this.ContentApplicationService.Value.GetCurrentVersionAsync(CmsRegionEnum.Legal).Result;

            TextViewModel model = new TextViewModel
            {
                Text = cmsVersion.ContentBody,
                IsExport = false
            };

            return this.PartialView("_Legal", model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult LegalPdf()
        {
            CmsVersionDto cmsVersion = this.ContentApplicationService.Value.GetCurrentVersionAsync(CmsRegionEnum.Legal).Result;

            this.ViewData.Model = new TextViewModel
            {
                Text = cmsVersion.ContentBody,
                IsExport = true
            };

            string fileName = ReplacementUtility.ReplaceWhiteSpace(ReplacementUtility.RemoveNonAlphaNumeric(this.ClientDto.ClientName), "_") + "_Legal.pdf";
            this.WritePdfInline(this.PdfConverter.Value.CreatePdfFromHtml(this.ClientDto.ClientName + " Legal", this.RenderViewToString("~/Views/Legal/_Legal.cshtml", "~/Views/Shared/_LayoutPrint.cshtml")), fileName);

            return this.Json(new { }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Privacy()
        {
            return this.View(this.GetPrivacy());
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult PrivacyPartial()
        {
            return this.PartialView("_Privacy", this.GetPrivacy());
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult PrivacyPdf()
        {
            this.ViewData.Model = this.GetPrivacy(false);

            string fileName = ReplacementUtility.ReplaceWhiteSpace(ReplacementUtility.RemoveNonAlphaNumeric(this.ClientDto.ClientName), "_") + "_PrivacyPolicy.pdf";
            this.WritePdfInline(this.PdfConverter.Value.CreatePdfFromHtml(this.ClientDto.ClientName + " Privacy Policy", this.RenderViewToString("~/Views/Legal/_Privacy.cshtml", "~/Views/Shared/_LayoutPrint.cshtml")), fileName);

            return this.Json(new { }, JsonRequestBehavior.AllowGet);
        }

        private TextViewModel GetPrivacy(bool showButton = true)
        {
            CmsVersionDto cmsVersion = this.ContentApplicationService.Value.GetCurrentVersionAsync(CmsRegionEnum.Privacy).Result;

            return new TextViewModel
            {
                Text = cmsVersion.ContentBody,
                IsExport = !showButton
            };
        }

        /// <summary>
        /// If incoming ID is formatted as a finance plan public ID (PHI), 
        /// lookup the finance plan offer ID accordingly. Support legacy contract number 
        /// format for users with access to those links.
        /// </summary>
        private int? GetFinancePlanOfferId(string id)
        {
            int? financePlanOfferId;
            bool isFinancePlanPublicIdPhiFormat = FinancePlanPublicIdPhiSource.IsValidFormat(id);

            if (isFinancePlanPublicIdPhiFormat)
            {
                financePlanOfferId = 
                    this._financePlanApplicationService.Value
                        .GetFinancePlanOfferId(id, this.CurrentGuarantorId);

                return financePlanOfferId;
            }

            financePlanOfferId = 
                this.CreditAgreementApplicationService.Value
                    .GetFinancePlanOfferIdFromContractNumber(id, this.CurrentGuarantorId);

            return financePlanOfferId;
        }
    }
}

Presentation/Web/Ivh.Web.Patient/Views/Legal/IndexAuth.cshtml
@using Ivh.Common.VisitPay.Constants
@model Ivh.Common.Web.Models.Shared.ContentMenuViewModel

@{
    Layout = "~/Views/Shared/_LayoutPatientSidebar.cshtml";
}

@Html.VpPageHeading(Html.TextRegion(TextRegionConstants.LegalAgreementsPageHeading))
@Html.Partial("_Index", Model)

Presentation/Web/Ivh.Web.Patient/Views/Legal/IndexPublic.cshtml
@using Ivh.Common.VisitPay.Constants
@model Ivh.Common.Web.Models.Shared.ContentMenuViewModel

@{
    Layout = "~/Views/Shared/_LayoutPublic.cshtml";
}

@Html.VpPageHeading(Html.TextRegion(TextRegionConstants.LegalAgreementsPageHeading))
@Html.Partial("_Index", Model)

Presentation/Web/Ivh.Web.Patient/Views/Legal/IndexPublicAlt.cshtml
@using Ivh.Common.VisitPay.Constants
@using Ivh.Common.Web.Models.Shared
@model ContentMenuViewModel
@{
    Layout = "~/Views/Shared/_LayoutAltLogin.cshtml";
}

<div class="flex-body">
    <div class="content-box box">
        <div>
            <h1>@Html.TextRegion(TextRegionConstants.LegalAgreementsPageHeading)</h1>
            @Html.Partial("_Index", Model)
        </div>
    </div>
</div>

Presentation/Web/Ivh.Web.Patient/Views/Legal/TermsOfUse.cshtml
@using Ivh.Common.VisitPay.Constants
@model Ivh.Common.Web.Models.Shared.TermsOfUseViewModel

@Html.VpPageHeading(Html.TextRegion(TextRegionConstants.TermsOfUse))
@Html.Partial("~/Views/Legal/_Terms.cshtml", Model)

Presentation/Web/Ivh.Web.Patient/Views/Legal/_CreditAgreement.cshtml
@model Ivh.Common.Web.Models.Legal.CreditAgreementViewModel
@{
    object parameters = new {o = Model.FinancePlanOfferId};
}

<div id="modalCreditAgreement" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="@Html.TextRegion(TextRegionConstants.Close)"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@Html.Raw(Model.Title)</h4>
            </div>
            <div class="modal-body">
                <section style="text-align: justify;">
                    <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "CreditAgreementPdf", "Legal", parameters, new { @class = "btn btn-primary", role = "button", target = "_blank" })</p>
                    @Html.Raw(Model.Text)
                </section>
            </div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-primary" data-dismiss="modal">@Html.TextRegion(TextRegionConstants.Close)</button>
            </div>
        </div>
    </div>
</div>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_CreditAgreementPage.cshtml
@model Ivh.Common.Web.Models.Legal.CreditAgreementViewModel
@{
    object parameters = new { o = Model.FinancePlanOfferId };
}

<section style="text-align: justify;">
    <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "CreditAgreementPdf", "Legal", parameters, new { @class = "btn btn-primary", role = "button", target = "_blank" })</p>
    @Html.Raw(Model.Text)
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_CreditAgreementPdf.cshtml
@model Ivh.Common.Web.Models.Legal.CreditAgreementViewModel

<section style="text-align: justify;">
    @Html.Raw(Model.Text)
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_Esign.cshtml
@model Ivh.Common.Web.Models.Shared.TextViewModel

<section id="section-esign">
    @if (IsFeatureEnabled(VisitPayFeatureEnum.FeatureDebrandedUiIsEnabled))
    {
        Html.TextRegion(TextRegionConstants.UsabilityTerms);
    }
    else
    {
        if (!Model.IsExport)
        {
            <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "EsignPdf", "Legal", new { @class = "btn btn-primary", role = "button", target = "_blank" })</p>
        }
        @Html.Raw(Model.Text)
    }
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_Index.cshtml
@using Ivh.Common.Web.Models.Shared
@model ContentMenuViewModel

<section id="section-legal-agreements">
    <ul>
        @foreach (ContentMenuItemViewModel item in Model.ContentMenuItems)
        {
            <li><a href="@item.LinkUrl" title="@item.LinkText" target="@item.Target">@item.LinkText</a></li>
        }
    </ul>
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_Legal.cshtml
@using Ivh.Common.VisitPay.Constants
@using Ivh.Common.VisitPay.Enums
@model Ivh.Common.Web.Models.Shared.TextViewModel

<section style="text-align: justify;">
    @if (IsFeatureEnabled(VisitPayFeatureEnum.FeatureDebrandedUiIsEnabled))
    {
        Html.TextRegion(TextRegionConstants.UsabilityTerms);
    }
    else
    {
        if (!Model.IsExport)
        {
            <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "LegalPdf", "Legal", new { @class = "btn btn-primary", role = "button", target = "_blank" })</p>
        }
        @Html.Raw(Model.Text)
    }
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_Privacy.cshtml
@using Ivh.Common.VisitPay.Constants
@using Ivh.Common.VisitPay.Enums
@model Ivh.Common.Web.Models.Shared.TextViewModel

<section style="text-align: justify;">
    @if (IsFeatureEnabled(VisitPayFeatureEnum.FeatureDebrandedUiIsEnabled))
    {
        Html.TextRegion(TextRegionConstants.UsabilityTerms);
    }
    else
    {
        if (!Model.IsExport)
        {
            <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "PrivacyPdf", "Legal", new { @class = "btn btn-primary", role = "button", target = "_blank" })</p>
        }
        @Html.Raw(Model.Text)
    }
</section>

Presentation/Web/Ivh.Web.Patient/Views/Legal/_Terms.cshtml
@using Ivh.Common.VisitPay.Constants
@using Ivh.Common.VisitPay.Enums
@model Ivh.Common.Web.Models.Shared.TermsOfUseViewModel

<section id="section-terms">
    @if (IsFeatureEnabled(VisitPayFeatureEnum.FeatureDebrandedUiIsEnabled))
    {
        Html.TextRegion(TextRegionConstants.UsabilityTerms);
    }
    else
    {
        if (!Model.IsExport)
        {
            <p style="text-align: center;">@Html.ActionLink(Html.TextRegion(TextRegionConstants.PrintOrSaveAsPdf), "TermsPdf", "Legal", new {@class = "btn btn-primary", role = "button", target = "_blank"})</p>
        }
        <h3>@Html.TextRegion(TextRegionConstants.DateOfLastModification): @Model.UpdatedDate</h3>
        @Html.Raw(Model.Text)
        <h3>@Html.TextRegion(TextRegionConstants.DateOfLastModification): @Model.UpdatedDate</h3>
    }
    </section>