Presentation/Web/Ivh.Web.Client/Models/Sso/ClientSsoProviderWithUserSettingsViewModel.cs
namespace Ivh.Web.Client.Models.Sso
{
    using Common.Web.Models.Sso;

    public class ClientSsoProviderWithUserSettingsViewModel : SsoProviderWithUserSettingsViewModel
    {
        public int VisitPayUserId { get; set; }
        public string SourceSystemKey { get; set; }
        public bool IsUserEligible { get; set; }
    }
}

Presentation/Web/Ivh.Web.Client/Controllers/SsoController.cs
namespace Ivh.Web.Client.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Application.Content.Common.Interfaces;
    using Application.Core.Common.Dtos;
    using Application.Core.Common.Interfaces;
    using Attributes;
    using AutoMapper;
    using Common.Base.Enums;
    using Common.Cache;
    using Common.VisitPay.Enums;
    using Common.VisitPay.Strings;
    using Common.Web.Controllers;
    using Common.Web.Filters;
    using Common.Web.Interfaces;
    using Common.Web.Models.Shared;
    using Microsoft.AspNet.Identity;
    using Models.Sso;

    [Authorize(Roles = VisitPayRoleStrings.System.Client + "," + VisitPayRoleStrings.Admin.Administrator)]
    [VpAuthorize(Roles = VisitPayRoleStrings.Csr.CSR + "," + VisitPayRoleStrings.Csr.UserAdmin + "," + VisitPayRoleStrings.Csr.SupportView + "," + VisitPayRoleStrings.Csr.SupportAdmin)]
    [RequireFeatureAny(VisitPayFeatureEnum.MyChartSso, VisitPayFeatureEnum.HealthEquityFeature)]
    public class SsoController : BaseSsoController
    {
        private readonly Lazy<IVisitPayUserApplicationService> _visitPayUserApplicationService;

        public SsoController(Lazy<IBaseControllerService> baseControllerService,
            Lazy<ISsoApplicationService> ssoApplicationService,
            Lazy<IContentApplicationService> contentApplicationService,
            Lazy<IGuarantorApplicationService> guarantorApplicationService,
            Lazy<IVisitPayUserApplicationService> visitPayUserApplicationService,
            Lazy<IDistributedCache> distributedCache
            )
            : base(
                baseControllerService,
                ssoApplicationService,
                contentApplicationService,
                guarantorApplicationService,
                distributedCache)
        {
            this._visitPayUserApplicationService = visitPayUserApplicationService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Settings(int visitPayUserId)
        {
            return this.PartialView("_SettingsModal", this.GetSettingsModel(visitPayUserId));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> DeclineConfirmation()
        {
            return this.Json(Mapper.Map<CmsViewModel>(await this.ContentApplicationService.Value.GetCurrentVersionAsync(CmsRegionEnum.SsoDeclineConfirmation)));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult Decline(SsoProviderEnum ssoProvider, int visitPayUserId)
        {
            this.Decline(visitPayUserId, ssoProvider, this.CurrentUserId);

            return this.PartialView("_Settings", this.GetSettingsModel(visitPayUserId).FirstOrDefault(x => x.SsoProviderId == (int) ssoProvider));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult Ignore(SsoProviderEnum ssoProvider, bool isIgnored, int visitPayUserId)
        {
            this.Ignore(visitPayUserId, ssoProvider, isIgnored, this.CurrentUserId);

            return this.PartialView("_Settings", this.GetSettingsModel(visitPayUserId).FirstOrDefault(x => x.SsoProviderId == (int) ssoProvider));
        }

        private List<ClientSsoProviderWithUserSettingsViewModel> GetSettingsModel(int visitPayUserId)
        {
            int vpGuarantorId = this._visitPayUserApplicationService.Value.GetGuarantorIdFromVisitPayUserId(visitPayUserId);

            IList<SsoProviderWithUserSettingsDto> providersWithSettings = this.SsoApplicationService.Value.GetAllProvidersWithUserSettings(visitPayUserId);

            List<ClientSsoProviderWithUserSettingsViewModel> model = Mapper.Map<List<ClientSsoProviderWithUserSettingsViewModel>>(providersWithSettings);

            model.ForEach(setting =>
            {
                setting.IsUserEligible = (SsoProviderEnum) setting.SsoProviderId != SsoProviderEnum.HealthEquityOutbound || this._visitPayUserApplicationService.Value.IsUserEligibleForHealthEquityOutboundSso(vpGuarantorId).GetValueOrDefault(false);
                setting.Body = this.CmsView(setting, true);
                setting.VisitPayUserId = visitPayUserId;
            });

            return model;
        }
    }
}

Presentation/Web/Ivh.Web.Client/Views/Sso/_Settings.cshtml
@model Ivh.Web.Client.Models.Sso.ClientSsoProviderWithUserSettingsViewModel


<h2>
    @ClientDto.ClientBrandName @Model.SsoProviderName Single Sign-On
    @if (!string.IsNullOrEmpty(Model.SourceSystemKey))
    {
        <span>@Model.SourceSystemKeyLabel: @Model.SourceSystemKey</span>
    }
</h2>
<div class="provider">
    @if (Model.IsUserEligible)
    {
        if (Model.IsAccepted)
        {
            <div class="accepted">
                @using (Html.BeginForm("Decline", "Sso", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("ssoProvider", Model.SsoProviderId)
                    @Html.Hidden("visitPayUserId", Model.VisitPayUserId)
                    <div>
                        <p>@Html.Raw(Model.Body.ContentBody)</p>
                    </div>
                    <hr/>
                    <p class="text-center">
                        <button type="button" class="btn btn-primary" id="btnOff">Disable @Model.SsoProviderName Single Sign-On</button>
                    </p>
                    <p class="text-center">
                        <em>Terms Accepted: @Model.ActionDateTime</em>
                    </p>
                }
            </div>
        }
        else
        {
            <div class="declined">
                @using (Html.BeginForm("Ignore", "Sso", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("ssoProvider", Model.SsoProviderId)
                    @Html.Hidden("visitPayUserId", Model.VisitPayUserId)
                    <div>
                        <p>@Html.Raw(Model.Body.ContentBody)</p>
                    </div>
                    if (Model.IsDeclined)
                    {
                        <hr/>
                        if (!Model.EnableFromManageSso)
                        {
                            <p class="text-center">
                                @Html.CheckBoxFor(m => Model.IsIgnored, Model.IsIgnored)
                                @Html.LabelFor(m => Model.IsIgnored, new {style = "font-weight: bold;"})
                            </p>
                        }
                        <p class="text-center">
                            <em>Declined: @Model.ActionDateTime by @Model.ActionVisitPayUser</em>
                        </p>
                    }
                }
            </div>
        }
    }
    else
    {
        <div class="alert alert-info">@Model.SsoProviderName Single Sign-On (SSO) is not available for this guarantor at this time.</div>
    }
    <br>
</div>

Presentation/Web/Ivh.Web.Client/Views/Sso/_SettingsModal.cshtml
@using Ivh.Web.Client.Models.Sso
@model IList<ClientSsoProviderWithUserSettingsViewModel>

<div id="modalManageSso" class="modal modal-vcenter fade" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                <h4 class="modal-title">
                    Manage Single Sign-On
                </h4>
            </div>
            <div class="modal-body">
                @foreach (ClientSsoProviderWithUserSettingsViewModel item in Model)
                {
                    <div>
                        @Html.Partial("_Settings", item)
                    </div>
                }
                <hr/>
                <p class="text-center">Your view/action on this content is logged for audit purposes. </p>
            </div>
        </div>
    </div>
</div>