Presentation/Web/Ivh.Web.Patient/Controllers/MonitoringController.cs
namespace Ivh.Web.Patient.Controllers
{
    using System;
    using Application.Content.Common.Interfaces;
    using Application.Monitoring.Common.Interfaces;
    using Application.Settings.Common.Interfaces;
    using Common.Web.Controllers;
    using Common.Web.Filters;
    using Domain.Settings.Interfaces;

    [ContentSecurityPolicyFilter(false)]
    public class MonitoringController : BaseMonitoringController
    {
        public MonitoringController(
             Lazy<ISystemHealthApplicationService> monitoringApplicationService,
             Lazy<IApplicationSettingsService> applicationSettingsService,
             Lazy<ISettingsApplicationService> settingsApplicationService,
             Lazy<IContentApplicationService> contentApplicationService
             ) : base(monitoringApplicationService, applicationSettingsService, settingsApplicationService, contentApplicationService)
        {

        }
    }
}

Presentation/Web/Ivh.Web.Patient/Views/Monitoring/SystemHealth.cshtml
@using System.Web.Mvc.Html
@using Ivh.Common.Base.Formatters
@model Ivh.Common.Web.Models.Monitoring.SystemHealthViewModel
@{
    /**/

    Layout = null;
}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>System Health</title>
    <meta http-equiv="refresh" content="5">
    <style type="text/css">
        .Table {
            display: table;
        }

        .Title {
            display: table-caption;
            text-align: center;
            font-weight: bold;
            font-size: larger;
        }

        .Heading {
            display: table-row;
            font-weight: bold;
            text-align: center;
        }

        .Row {
            display: table-row;
        }

        .Cell {
            display: table-cell;
            border: solid;
            border-width: thin;
            padding-left: 5px;
            padding-right: 5px;
        }

        .Raw {
            display: inline-block;
            border: solid 1px #000;
            min-height: 200px;
            width: 500px;
        }
    </style>

</head>
<body>
    <div class="Table">
        <div class="Title">
            <p>System Health <a href="@Url.Action("SystemInfo", "Monitoring")" title="SysInfo">System Info</a></p>
        </div>
        <div class="Heading">
            <div class="Cell">
                <p>Metric</p>
            </div>
            <div class="Cell">
                <p>Value</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Client)</p>
            </div>
            <div class="Cell">
                <p>@Model.Client</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Environment)</p>
            </div>
            <div class="Cell">
                <p>@Model.Environment</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Application)</p>
            </div>
            <div class="Cell">
                <p>@Model.Application</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.AppVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.AppVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ClientDataApiVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.ClientDataApiVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.SecurePanApiVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.SecurePanApiVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ClientSettingsHash)</p>
            </div>
            <div class="Cell">
                <p>@Model.ClientSettingsHash</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ReleaseBuild)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.ReleaseBuild ? "green" : "red")">
                <p>@Model.ReleaseBuild</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Settings)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.Settings ? "green" : "red")">
                <p>@Model.Queue</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Content)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.Content ? "green" : "red")">
                <p>@Model.Queue</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Queue)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.Queue ? "green" : "red")">
                <p>@Model.Queue</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.MemoryCache)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.MemoryCache ? "green" : "red")">
                <p>@Model.MemoryCache</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.DistributedCache)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.DistributedCache ? "green" : "red")">
                <p>@Model.DistributedCache</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ApplicationConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.ApplicationConnect ? "green" : "red")">
                <p>@Model.ApplicationConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.GuestPayConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.GuestPayConnect ? "green" : "red")">
                <p>@Model.GuestPayConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.LogConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.LogConnect ? "green" : "red")">
                <p>@Model.LogConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.StorageConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.StorageConnect ? "green" : "red")">
                <p>@Model.StorageConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.QuartzConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.QuartzConnect ? "green" : "red")">
                <p>@Model.QuartzConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.CdiEtlConnect)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.CdiEtlConnect ? "green" : "red")">
                <p>@Model.CdiEtlConnect</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.UniversalProcessor)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.UniversalProcessor ? "green" : "red")">
                <p>@Model.UniversalProcessor</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ScoringProcessor)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.ScoringProcessor ? "green" : "red")">
                <p>@Model.ScoringProcessor</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ClientReportsServer)</p>
            </div>
            <div class="Cell" style="background-color: @(Model.ClientReportsServer ? "green" : "yellow")">
                <p>@Model.ClientReportsServer (beta - coming soon)</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Raw)</p>
            </div>
            <div class="Raw" contenteditable="true">
                <pre>@Model.Raw</pre>
            </div>
        </div>
    </div>
</body>
</html>

Presentation/Web/Ivh.Web.Patient/Views/Monitoring/SystemInfo.cshtml
@using System.Web.Mvc.Html
@using Ivh.Common.Base.Formatters
@model Ivh.Common.Web.Models.Monitoring.SystemInfoViewModel
@{
    /**/

    Layout = null;
}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>System Info</title>
    <meta http-equiv="refresh" content="60">
    <style type="text/css">
        .Table {
            display: table;
        }

        .Title {
            display: table-caption;
            text-align: center;
            font-weight: bold;
            font-size: larger;
        }

        .Heading {
            display: table-row;
            font-weight: bold;
            text-align: center;
        }

        .Row {
            display: table-row;
        }

        .Cell {
            display: table-cell;
            border: solid;
            border-width: thin;
            padding-left: 5px;
            padding-right: 5px;
        }

        .Raw {
            display: inline-block;
            border: solid 1px #000;
            min-height: 200px;
            width: 500px;
        }
    </style>

</head>
<body>
    <div class="Table">
        <div class="Title">
            <p>System Info <a href="@Url.Action("SystemHealth", "Monitoring")" title="SysInfo">System Health</a></p> 
        </div>
        <div class="Heading">
            <div class="Cell">
                <p>Metric</p>
            </div>
            <div class="Cell">
                <p>Value</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Client)</p>
            </div>
            <div class="Cell">
                <p>@Model.Client</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Environment)</p>
            </div>
            <div class="Cell">
                <p>@Model.Environment</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Application)</p>
            </div>
            <div class="Cell">
                <p>@Model.Application</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.AppVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.AppVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ClientDataApiVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.ClientDataApiVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.SecurePanApiVersion)</p>
            </div>
            <div class="Cell">
                <p>@Model.SecurePanApiVersion</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.ClientSettingsHash)</p>
            </div>
            <div class="Cell">
                <p>@Model.ClientSettingsHash</p>
            </div>
        </div>
        <div class="Row">
            <div class="Cell">
                <p>@Html.LabelFor(m => m.Raw)</p>
            </div>
            <div class="Raw" contenteditable="true">
                <pre>@Model.Raw</pre>
            </div>
        </div>
    </div>
</body>
</html>